2025-08-05 12:32:52,254 - INFO - User Hirithik Pranav logged in
2025-08-05 12:32:52,254 - INFO - Data processed: good_data
2025-08-05 12:32:52,254 - INFO - User Hirithik Pranav logged out
2025-08-05 12:33:10,102 - INFO - User Hirithik Pranav logged in
2025-08-05 12:33:10,102 - ERROR - Error processing data: Invalid data
Traceback (most recent call last):
  File "/Users/hirithikpranavbalusamy/Documents/Code/CodeBasics Tutorials/Logging/logging_2.py", line 15, in process_data
    raise ValueError("Invalid data")
ValueError: Invalid data
2025-08-05 12:33:10,103 - INFO - User Hirithik Pranav logged out
